### ISSUE TITLE
Decide on update strategy for Gen3-Helm

### ISSUE THREAD

**Issue by lbeckman314** [ACED-IDP/gen3-helm#11]
![Image](https://user-images.githubusercontent.com/15309567/245608355-c03145eb-d901-4176-8de7-4a65aaa514be.png)

**Comment by lbeckman314** [comment]
# Gen3-Helm Branching Strategy
- Based on [Gitflow convention](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
- Pulls in changes from:
     - upstream/master to develop
     - fix/foo to develop
     - feature/foo to develop
     - develop to release
     - release to master
     - master to aced-idp.org

![dev-Copy of Helm drawio(1)](https://github.com/ACED-IDP/gen3-helm/assets/15309567/f1f5a77c-321e-45fa-8c40-bd980e4d2bbf)

**Comment by lbeckman314** [comment]
# Proposal: Gen3-Helm Branching Strategy (no release branch)
- Based on [Gitflow convention](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
- Pulls in changes from:
     - upstream/master to develop
     - fix/foo to develop
     - feature/foo to develop
     - develop to master
     - master to aced-idp.org


![dev-Gen3-Helm drawio](https://github.com/ACED-IDP/gen3-helm/assets/15309567/764ace8a-0a3c-4006-9cb2-a23650d6b9e0)

**Comment by bwalsh** [comment]
Slight preference for the option with the release branch. That would correspond with a release to the staging environment, prior to a deployment from main to production

**Comment by lbeckman314** [comment]
Sounds good!
