### ISSUE TITLE
Test with wasabi S3 

### ISSUE THREAD

**Issue by bwalsh** [ACED-IDP/gen3-helm#25]
![image](https://github.com/ACED-IDP/gen3-helm/assets/47808/b4011ee0-3030-4f9b-b672-272609e6a697)
https://knowledgebase.wasabi.com/hc/en-us/articles/360019677192-Creating-a-Wasabi-API-Access-Key-Set

**Comment by lbeckman314** [comment]
Created an ACED test instance here: https://console.wasabisys.com/

**Comment by lbeckman314** [comment]
Also worth testing new multipart upload with Fence and data-client branches: 

Branches for multipart upload:
- https://github.com/uc-cdis/fence/pull/1112
- https://github.com/uc-cdis/cdis-data-client/pull/123

**Comment by lbeckman314** [comment]
Tested successfully on [Wasabi](https://console.wasabisys.com/dashboard) with single-user test account, initial [speed test](https://github.com/ACED-IDP/benchwarmer) results on Wiki:
> https://github.com/ACED-IDP/gen3-helm/wiki/4.-Data-Upload
